import type { Product } from "@/lib/products";

/** Ruta de imagen por id y subcarpeta */
const img = (sub: string, id: string) => `/images/productos/${sub}/${id}.png`;

/** Ruta de video por id y subcarpeta */
const vid = (sub: string, id: string) => `/images/productos/${sub}/${id}.mp4`;

/**
 * Dataset de referencia del catálogo Celisan.
 *
 * Imágenes: subir archivos .png a /public/images/productos/<id>.png
 * Videos:   subir archivos .mp4 a /public/images/productos/<id>.mp4
 */
export const catalogSeed: Product[] = [
  // ── Waffles Congelados ────────────────────────────────────────────────────
  // Dulces o Salados: tienen selector de sabor
  {
    id: "wc-dulces-x2",
    name: "Waffles Salados o Dulces de Vainilla x 2",
    category: "Waffles Congelados",
    price: 5500,
    description: "Por 2 unidades.\nMedida: 20 x 10 cm",
    image: img("congelados", "wc-vainilla-x2"),
    stock: 1,
  },
  {
    id: "wc-dulces-x4",
    name: "Waffles Salados o Dulces de Vainilla x 4",
    category: "Waffles Congelados",
    price: 9990,
    description: "Por 4 unidades.\nMedida: 20 x 20 cm",
    image: img("congelados", "wc-vainilla-x4"),
    stock: 1,
  },
  // Chocolate: solo dulce, sin selector de sabor
  {
    id: "wc-choc-x2",
    name: "Waffles Dulces de Chocolate x 2",
    category: "Waffles Congelados",
    price: 6000,
    description: "Por 2 unidades.\nMedida: 20 x 10 cm",
    image: img("congelados", "wc-choc"),
    stock: 1,
  },
  {
    id: "wc-choc-x4",
    name: "Waffles Dulces de Chocolate x 4",
    category: "Waffles Congelados",
    price: 11000,
    description: "Por 4 unidades.\nMedida: 20 x 20 cm",
    image: img("congelados", "wc-choc"),
    stock: 1,
  },

  // ── Waffles con Cobertura ─────────────────────────────────────────────────
  {
    id: "wcb-veggie",
    name: "Waffle Salado Morado Veggie",
    category: "Waffles con Cobertura",
    price: 13990,
    description:
      "Berenjena asada, tomates y queso sobre waffle artesanal sin gluten.",
    image: "/images/productos/cobertura/waffle-berenjena.png",
    stock: 1,
  },
  {
    id: "wcb-jyq",
    name: "Waffle Salado con Jamón y Queso",
    category: "Waffles con Cobertura",
    price: 13990,
    description: "Jamón y queso fundido en waffle recién hecho sin gluten.",
    image: "/images/productos/cobertura/waffle-jyqueso.png",
    stock: 1,
  },
  {
    id: "wcb-banana",
    name: "Waffle con Banana, Dulce de leche y chocolate",
    category: "Waffles con Cobertura",
    price: 13990,
    description:
      "Banana con dulce de leche e hilos de chocolate sobre waffle artesanal sin gluten.",
    image: "/images/productos/cobertura/waffle-dulce.png",
    stock: 1,
  },
  {
    id: "wcb-frutos",
    name: "Waffle con Frutos Rojos y crema chantilly",
    category: "Waffles con Cobertura",
    price: 15990,
    description:
      "Mix de frutos rojos con crema chantilly sobre waffle artesanal sin gluten.",
    image: "/images/productos/cobertura/waffle-frutos.png",
    stock: 1,
  },

  // ── Viandas Soy Sin Gluten ────────────────────────────────────────────────
  {
    id: "ssg-lasagna",
    name: "Lasagna con salsa bolognesa",
    category: "Viandas Soy Sin Gluten",
    price: 11600,
    description: "",
    image: img("viandas", "ssg-lasagna"),
    stock: 1,
  },
  {
    id: "ssg-sorrentinos-jyq",
    name: "Sorrentinos de jamón y queso con salsa roja",
    category: "Viandas Soy Sin Gluten",
    price: 10800,
    description: "",
    image: img("viandas", "ssg-sorrentinos"),
    stock: 1,
  },
  {
    id: "ssg-sorrentinos-verdura",
    name: "Sorrentinos de verdura con salsa roja",
    category: "Viandas Soy Sin Gluten",
    price: 10800,
    description: "",
    image: img("viandas", "ssg-sorrentinos"),
    stock: 1,
  },
  {
    id: "ssg-canelones",
    name: "Canelones de carne y acelga con salsa bolognesa",
    category: "Viandas Soy Sin Gluten",
    price: 10800,
    description: "",
    image: img("viandas", "ssg-canelones"),
    stock: 1,
  },
  {
    id: "ssg-sand-bondiola",
    name: "Sandwich de bondiola cerdo con verduras y queso",
    category: "Viandas Soy Sin Gluten",
    price: 8600,
    description: "",
    image: img("viandas", "ssg-sand-bondiola"),
    stock: 1,
  },
  {
    id: "ssg-sand-hamburguesa",
    name: "Sandwich Hamburguesa (casera / queso)",
    category: "Viandas Soy Sin Gluten",
    price: 7200,
    description: "",
    image: img("viandas", "ssg-sand-hamburguesa"),
    stock: 1,
  },
  {
    id: "ssg-sand-pollo",
    name: "Sandwich de pollo con verdeo, queso azul y cebolla",
    category: "Viandas Soy Sin Gluten",
    price: 7500,
    description: "",
    image: img("viandas", "ssg-sand-pollo"),
    stock: 1,
  },
  {
    id: "ssg-sand-vegetales",
    name: "Sandwich de vegetales asados con queso",
    category: "Viandas Soy Sin Gluten",
    price: 6500,
    description: "",
    image: img("viandas", "ssg-sand-vegetales"),
    stock: 1,
  },
  {
    id: "ssg-sand-jyq",
    name: "Sandwich de jamón y queso",
    category: "Viandas Soy Sin Gluten",
    price: 7200,
    description: "",
    image: img("viandas", "ssg-sand-jyq"),
    stock: 1,
  },
  {
    id: "ssg-tarta-jyq",
    name: "1/2 Tarta de jamón y queso",
    category: "Viandas Soy Sin Gluten",
    price: 11500,
    description: "",
    image: img("viandas", "ssg-tarta-jyq"),
    stock: 1,
  },
  {
    id: "ssg-tarta-anco",
    name: "1/2 Tarta de anco, acelga y queso",
    category: "Viandas Soy Sin Gluten",
    price: 12200,
    description: "",
    image: img("viandas", "ssg-tarta-anco"),
    stock: 1,
  },
  {
    id: "ssg-tarta-zapallito",
    name: "1/2 Tarta de zapallito, cebolla y queso",
    category: "Viandas Soy Sin Gluten",
    price: 11500,
    description: "",
    image: img("viandas", "ssg-tarta-zapallito"),
    stock: 1,
  },
  {
    id: "ssg-tarta-pollo",
    name: "1/2 Tarta de pollo y acelga",
    category: "Viandas Soy Sin Gluten",
    price: 12200,
    description: "",
    image: img("viandas", "ssg-tarta-pollo"),
    stock: 1,
  },
  {
    id: "ssg-pizza",
    name: "Pizza lista x 4 porciones",
    category: "Viandas Soy Sin Gluten",
    price: 7900,
    description: "",
    image: img("viandas", "ssg-pizza"),
    stock: 1,
  },
  {
    id: "ssg-emp-dulce",
    name: "Empanadas de carne dulce x 3 unidades",
    category: "Viandas Soy Sin Gluten",
    price: 7200,
    description: "",
    image: img("viandas", "ssg-emp-dulce"),
    stock: 1,
  },
  {
    id: "ssg-emp-salada",
    name: "Empanadas de carne salada x 3 unidades",
    category: "Viandas Soy Sin Gluten",
    price: 7200,
    description: "",
    image: img("viandas", "ssg-emp-salada"),
    stock: 1,
  },
  {
    id: "ssg-emp-arabes",
    name: "Empanadas árabes x 3 unidades",
    category: "Viandas Soy Sin Gluten",
    price: 7200,
    description: "",
    image: img("viandas", "ssg-emp-arabes"),
    stock: 1,
  },
  {
    id: "ssg-tacos",
    name: "Tacos de verdura x 3 unidades",
    category: "Viandas Soy Sin Gluten",
    price: 7900,
    description: "",
    image: img("viandas", "ssg-tacos"),
    stock: 1,
  },

  // ── Panificación y Pastas Soy Sin Gluten ───────────────────────────────────
  {
    id: "ppc-prepizzas",
    name: "Pre pizzas",
    category: "Panificación y Pastas Soy Sin Gluten",
    price: 2900,
    description: "",
    image: img("panificacion", "ppc-prepizzas"),
    stock: 1,
  },
  {
    id: "ppc-noquis",
    name: "Ñoquis crudos x 250gr",
    category: "Panificación y Pastas Soy Sin Gluten",
    price: 5800,
    description: "",
    image: img("panificacion", "ppc-noquis"),
    stock: 1,
  },
  {
    id: "ppc-sorrentinos-jyq",
    name: "Sorrentinos crudos de jamón y queso x 8 unidades",
    category: "Panificación y Pastas Soy Sin Gluten",
    price: 8600,
    description: "",
    image: img("panificacion", "ppc-sorrentinos-crudos"),
    stock: 1,
  },
  {
    id: "ppc-sorrentinos-verdura",
    name: "Sorrentinos crudos de verdura x 8 unidades",
    category: "Panificación y Pastas Soy Sin Gluten",
    price: 8600,
    description: "",
    image: img("panificacion", "ppc-sorrentinos-crudos"),
    stock: 1,
  },
  {
    id: "ppc-hamb-legumbres",
    name: "Hamburguesas de legumbres x 4 unidades",
    category: "Panificación y Pastas Soy Sin Gluten",
    price: 4000,
    description: "",
    image: img("panificacion", "ppc-hamb-legumbres"),
    stock: 1,
  },
  {
    id: "ppc-emp-crudas",
    name: "Empanadas crudas x 4 unidades",
    category: "Panificación y Pastas Soy Sin Gluten",
    price: 11500,
    description: "",
    image: img("panificacion", "ppc-emp-crudas"),
    stock: 1,
    available: false, // oculto temporalmente — cambiar a true para mostrar
  },
  {
    id: "ppc-medialunas",
    name: "Medialunas x 50gr.",
    category: "Panificación y Pastas Soy Sin Gluten",
    price: 2000,
    description: "",
    image: img("panificacion", "ppc-medialunas"),
    stock: 1,
  },
  {
    id: "ppc-mafalda",
    name: "Mafalda x unidad",
    category: "Panificación y Pastas Soy Sin Gluten",
    price: 2600,
    description: "",
    image: img("panificacion", "ppc-mafalda-1"),
    images: [
      img("panificacion", "ppc-mafalda-1"),
      img("panificacion", "ppc-mafalda-2"),
    ],
    stock: 1,
  },
  {
    id: "ppc-pan-lactal",
    name: "Tipo Pan Lactal x 700gr.",
    category: "Panificación y Pastas Soy Sin Gluten",
    price: 6500,
    description: "",
    image: img("panificacion", "ppc-pan-lactal"),
    stock: 1,
  },
  {
    id: "ppc-pan-baguette",
    name: "Pan baguette x 200gr.",
    category: "Panificación y Pastas Soy Sin Gluten",
    price: 2000,
    description: "",
    image: img("panificacion", "ppc-pan-baguette"),
    stock: 1,
  },
  {
    id: "ppc-pan-campo",
    name: "Pan de campo x 330 gr",
    category: "Panificación y Pastas Soy Sin Gluten",
    price: 4200,
    description: "",
    image: img("panificacion", "ppc-pan-campo"),
    stock: 1,
  },
  {
    id: "ppc-pan-panchos",
    name: "Pan de panchos x 2 unidades",
    category: "Panificación y Pastas Soy Sin Gluten",
    price: 2500,
    description: "",
    image: img("panificacion", "ppc-pan-panchos"),
    stock: 1,
  },
  {
    id: "ppc-pan-hamburguesa",
    name: "Pan hamburguesa x 130gr.",
    category: "Panificación y Pastas Soy Sin Gluten",
    price: 1500,
    description: "",
    image: img("panificacion", "ppc-pan-hamburguesa"),
    stock: 1,
  },

  // ── Desayunos ─────────────────────────────────────────────────────────────
  {
    id: "des-clasico-2",
    name: "Desayuno Clásico 2 cuadraditos",
    category: "Desayunos",
    price: 28000,
    description: "Porción 1 persona",
    image: img("desayunos", "des-clasico-2"),
    video: vid("desayunos", "des-clasico-2"),
    stock: 1,
  },
  {
    id: "des-clasico-4",
    name: "Desayuno Clásico 4 cuadraditos",
    category: "Desayunos",
    price: 48000,
    description: "Porción para compartir con otro",
    image: img("desayunos", "des-clasico-4"),
    video: vid("desayunos", "des-clasico-4"),
    stock: 1,
  },
  {
    id: "des-proteico-2",
    name: "Desayuno Proteico 2 cuadraditos",
    category: "Desayunos",
    price: 28000,
    description: "Porción para una persona",
    image: img("desayunos", "des-proteico-2"),
    video: vid("desayunos", "des-proteico-2"),
    stock: 1,
  },
  {
    id: "des-taza",
    name: "Adicional taza + cuchara",
    category: "Desayunos",
    price: 15000,
    description: "",
    image: img("desayunos", "des-taza"),
    stock: 1,
  },

  // ── Vianda Cumple ───────────────────────────────────────────────────────────
  {
    id: "vc-jyq-oreo",
    name: "Vianda Cumple JyQ / Oreo",
    category: "Vianda Cumple",
    price: 24000,
    description:
      "Contiene: cuadradito salado de jyq, cuadradito dulce de óreo con dulce de leche y copitos de chocolate, bolsita de pochoclos salados y juguito de naranja sin gluten",
    image: img("viandacumple", "vc-jyq-oreo"),
    video: "/images/productos/viandacumple/vianda-infantil.mp4",
    stock: 1,
  },
];
