import type { Product } from "@/lib/products";

const PLACEHOLDER = "/logo-celisan.png";

/** Ruta de imagen por id — subir el archivo con este nombre a /public/images/productos/ */
const img = (id: string) => `/images/productos/${id}.png`;

/**
 * Dataset de referencia del catálogo Celisan.
 * Fuente: lista de precios vigente (Menú listo, Panificados, Waffles, Desayunos).
 */
export const catalogSeed: Product[] = [
  // ── Menú listo · Línea Soy Sin Gluten ─────────────────────────────────────
  {
    id: "ssg-lasagna",
    name: "Lasagna con salsa bolognesa",
    category: "Línea Soy Sin Gluten",
    price: 11600,
    description: "",
    image: img("ssg-lasagna"),
    stock: 1,
  },
  {
    id: "ssg-sorrentinos",
    name: "Sorrentinos de jamón y queso con salsa roja",
    category: "Línea Soy Sin Gluten",
    price: 10800,
    description: "",
    image: img("ssg-sorrentinos"),
    stock: 1,
  },
  {
    id: "ssg-sorrentinos",
    name: "Sorrentinos de verdura con salsa roja",
    category: "Línea Soy Sin Gluten",
    price: 10800,
    description: "",
    image: img("ssg-sorrentinos"),
    stock: 1,
  },
  {
    id: "ssg-canelones",
    name: "Canelones de carne y acelga con salsa bolognesa",
    category: "Línea Soy Sin Gluten",
    price: 10800,
    description: "",
    image: img("ssg-canelones"),
    stock: 1,
  },
  {
    id: "ssg-sand-bondiola",
    name: "Sandwich de bondiola cerdo con verduras y queso",
    category: "Línea Soy Sin Gluten",
    price: 8600,
    description: "",
    image: img("ssg-sand-bondiola"),
    stock: 1,
  },
  {
    id: "ssg-sand-hamburguesa",
    name: "Sandwich Hamburguesa (casera / queso)",
    category: "Línea Soy Sin Gluten",
    price: 7200,
    description: "",
    image: img("ssg-sand-hamburguesa"),
    stock: 1,
  },
  {
    id: "ssg-sand-pollo",
    name: "Sandwich de pollo con verdeo, queso azul y cebolla",
    category: "Línea Soy Sin Gluten",
    price: 7500,
    description: "",
    image: img("ssg-sand-pollo"),
    stock: 1,
  },
  {
    id: "ssg-sand-vegetales",
    name: "Sandwich de vegetales asados con queso",
    category: "Línea Soy Sin Gluten",
    price: 6500,
    description: "",
    image: img("ssg-sand-vegetales"),
    stock: 1,
  },
  {
    id: "ssg-sand-jyq",
    name: "Sandwich de jamón y queso",
    category: "Línea Soy Sin Gluten",
    price: 7200,
    description: "",
    image: img("ssg-sand-jyq"),
    stock: 1,
  },
  {
    id: "ssg-tarta-jyq",
    name: "1/2 Tarta de jamón y queso",
    category: "Línea Soy Sin Gluten",
    price: 11500,
    description: "",
    image: img("ssg-tarta-jyq"),
    stock: 1,
  },
  {
    id: "ssg-tarta-anco",
    name: "1/2 Tarta de anco, acelga y queso",
    category: "Línea Soy Sin Gluten",
    price: 12200,
    description: "",
    image: img("ssg-tarta-anco"),
    stock: 1,
  },
  {
    id: "ssg-tarta-zapallito",
    name: "1/2 Tarta de zapallito, cebolla y queso",
    category: "Línea Soy Sin Gluten",
    price: 11500,
    description: "",
    image: img("ssg-tarta-zapallito"),
    stock: 1,
  },
  {
    id: "ssg-tarta-pollo",
    name: "1/2 Tarta de pollo y acelga",
    category: "Línea Soy Sin Gluten",
    price: 12200,
    description: "",
    image: img("ssg-tarta-pollo"),
    stock: 1,
  },
  {
    id: "ssg-pizza",
    name: "Pizza lista x 4 porciones",
    category: "Línea Soy Sin Gluten",
    price: 7900,
    description: "",
    image: img("ssg-pizza"),
    stock: 1,
  },
  {
    id: "ssg-emp-dulce",
    name: "Empanadas de carne dulce x 3 unidades",
    category: "Línea Soy Sin Gluten",
    price: 7200,
    description: "",
    image: img("ssg-emp-dulce"),
    stock: 1,
  },
  {
    id: "ssg-emp-salada",
    name: "Empanadas de carne salada x 3 unidades",
    category: "Línea Soy Sin Gluten",
    price: 7200,
    description: "",
    image: img("ssg-emp-salada"),
    stock: 1,
  },
  {
    id: "ssg-emp-arabes",
    name: "Empanadas árabes x 3 unidades",
    category: "Línea Soy Sin Gluten",
    price: 7200,
    description: "",
    image: img("ssg-emp-arabes"),
    stock: 1,
  },
  {
    id: "ssg-tacos",
    name: "Tacos de verdura x 3 unidades",
    category: "Línea Soy Sin Gluten",
    price: 7900,
    description: "",
    image: img("ssg-tacos"),
    stock: 1,
  },

  // ── Panificados y Pastas congeladas ───────────────────────────────────────
  {
    id: "ppc-prepizzas",
    name: "Pre pizzas",
    category: "Panificados y Pastas congeladas",
    price: 2900,
    description: "",
    image: img("ppc-prepizzas"),
    stock: 1,
  },
  {
    id: "ppc-noquis",
    name: "Ñoquis crudos x 250gr",
    category: "Panificados y Pastas congeladas",
    price: 5800,
    description: "",
    image: img("ppc-noquis"),
    stock: 1,
  },
  {
    id: "ppc-sorrentinos-crudos",
    name: "Sorrentinos crudos de jamón y queso x 8 unidades",
    category: "Panificados y Pastas congeladas",
    price: 8600,
    description: "",
    image: img("ppc-sorrentinos-crudos"),
    stock: 1,
  },
  {
    id: "ppc-sorrentinos-crudos",
    name: "Sorrentinos crudos de verdura x 8 unidades",
    category: "Panificados y Pastas congeladas",
    price: 8600,
    description: "",
    image: img("ppc-sorrentinos-crudos"),
    stock: 1,
  },
  {
    id: "ppc-hamb-legumbres",
    name: "Hamburguesas de legumbres x 4 unidades",
    category: "Panificados y Pastas congeladas",
    price: 4000,
    description: "",
    image: img("ppc-hamb-legumbres"),
    stock: 1,
  },
  {
    id: "ppc-emp-crudas",
    name: "Empanadas crudas x 4 unidades",
    category: "Panificados y Pastas congeladas",
    price: 11500,
    description: "",
    image: img("ppc-emp-crudas"),
    stock: 1,
  },
  {
    id: "ppc-medialunas",
    name: "Medialunas x 50gr.",
    category: "Panificados y Pastas congeladas",
    price: 2000,
    description: "",
    image: img("ppc-medialunas"),
    stock: 1,
  },
  {
    id: "ppc-mafalda",
    name: "Mafalda x unidad",
    category: "Panificados y Pastas congeladas",
    price: 2600,
    description: "",
    image: img("ppc-mafalda"),
    stock: 1,
  },
  {
    id: "ppc-pan-lactal",
    name: "Tipo Pan Lactal x 700gr.",
    category: "Panificados y Pastas congeladas",
    price: 6500,
    description: "",
    image: img("ppc-pan-lactal"),
    stock: 1,
  },
  {
    id: "ppc-pan-baguette",
    name: "Pan baguette x 200gr.",
    category: "Panificados y Pastas congeladas",
    price: 2000,
    description: "",
    image: img("ppc-pan-baguette"),
    stock: 1,
  },
  {
    id: "ppc-pan-campo",
    name: "Pan de campo x 330 gr",
    category: "Panificados y Pastas congeladas",
    price: 4200,
    description: "",
    image: img("ppc-pan-campo"),
    stock: 1,
  },
  {
    id: "ppc-pan-panchos",
    name: "Pan de panchos x 2 unidades",
    category: "Panificados y Pastas congeladas",
    price: 2500,
    description: "",
    image: img("ppc-pan-panchos"),
    stock: 1,
  },
  {
    id: "ppc-pan-hamburguesa",
    name: "Pan hamburguesa x 130gr.",
    category: "Panificados y Pastas congeladas",
    price: 1500,
    description: "",
    image: img("ppc-pan-hamburguesa"),
    stock: 1,
  },

  // ── Waffles Congelados ────────────────────────────────────────────────────
  {
    id: "wc-may-x4",
    name: "Waffles Salados o Dulces de vainillax 4",
    category: "Waffles Congelados",
    price: 9990,
    description: "Por 4 unidades.\nMedida: 20 x 20 cm",
    image: "/congeladox4.png",
    stock: 1,
  },
  {
    id: "wc-min-x2",
    name: "Waffles Salados o Dulces de vainilla x 2",
    category: "Waffles Congelados",
    price: 4100,
    description: "Por 2 unidades.\nMedida: 20 x 10 cm",
    image: "/congeladox2.png",
    stock: 1,
  },
  {
    id: "wc-min-x4",
    name: "Waffles Dulces de chocolate x 4",
    category: "Waffles Congelados",
    price: 11000,
    description: "Por 4 unidades.\nMedida: 20 x 20 cm",
    image: "/congeladox4.png",
    stock: 1,
  },
  {
    id: "wc-min-x4",
    name: "Waffles Dulces de chocolate x 2",
    category: "Waffles Congelados",
    price: 6000,
    description: "Por 2 unidades.\nMedida: 20 x 10 cm",
    image: "/congeladox4.png",
    stock: 1,
  },

  // ── Waffles con Cobertura ─────────────────────────────────────────────────
  {
    id: "wcb-veggie",
    name: "Waffle Salado Morado Veggie",
    category: "Waffles con Cobertura",
    price: 13990,
    description:
      "Berenjena asada, tomates y queso sobre waffle artesanal sin gluten.",
    image: "/waffle-berenjena.png",
    stock: 1,
  },
  {
    id: "wcb-jyq",
    name: "Waffle Salado con Jamón y Queso",
    category: "Waffles con Cobertura",
    price: 13990,
    description: "Jamón y queso fundido en waffle recién hecho sin gluten.",
    image: "/waffle-jyqueso.png",
    stock: 1,
  },
  {
    id: "wcb-banana",
    name: "Waffle con Banana, Dulce de leche y chocolate",
    category: "Waffles con Cobertura",
    price: 13990,
    description:
      "Banana con dulce de leche e hilos de chocolate sobre waffle artesanal sin gluten.",
    image: "/waffle-dulce.png",
    stock: 1,
  },
  {
    id: "wcb-frutos",
    name: "Waffle con Frutos Rojos y crema chantilly",
    category: "Waffles con Cobertura",
    price: 15990,
    description:
      "Mix de frutos rojos con crema chantilly sobre waffle artesanal sin gluten.",
    image: "/waffle-frutos.png",
    stock: 1,
  },

  // ── Desayunos ─────────────────────────────────────────────────────────────
  {
    id: "des-clasico-2",
    name: "Desayuno Clásico 2 cuadraditos",
    category: "Desayunos",
    price: 25000,
    description: "Porción 1 persona",
    image: img("des-clasico-2"),
    stock: 1,
  },
  {
    id: "des-clasico-4",
    name: "Desayuno Clásico 4 cuadraditos",
    category: "Desayunos",
    price: 44000,
    description: "Porción para compartir con otro",
    image: img("des-clasico-4"),
    stock: 1,
  },
  {
    id: "des-proteico-2",
    name: "Desayuno Proteico 2 cuadraditos",
    category: "Desayunos",
    price: 25000,
    description: "Porción para una persona",
    image: img("des-proteico-2"),
    stock: 1,
  },
  {
    id: "des-taza",
    name: "Adicional taza + cuchara",
    category: "Desayunos",
    price: 15000,
    description: "",
    image: img("des-taza"),
    stock: 1,
  },

  // ── Vianda Cumple ───────────────────────────────────────────────────────────
  {
    id: "vc-jyq-oreo",
    name: "Vianda Cumple JyQ / Oreo",
    category: "Vianda Cumple",
    price: 20000,
    description: "Contiene: cuadradito salado de jyq, cuadradito dulce de óreo con dulce de leche y copitos de chocolate, bolsita de pochoclos salados y juguito de naranja sin gluten",
    image: img("vc-jyq-oreo"),
    stock: 1,
  },
];
